name: frontend build CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # `yarn install`
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: check-all # `yarn check-all`
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build # `yarn build`
